#python

###### GLOBAL VARIABLES HERE ######
base = None
motor = None
arm = None
pendulum = None
U = None
# You can add variables here 
# as required by your implementation.
###################################
U = 0.00
time = 0.01
k = [14,1,20,3,49,9]

def sysCall_init():
    # do some initialization here
    # This function will be executed once when the simulation starts
    
    ####### ADD YOUR CODE HERE ######
    # Hint: Initialize the scene objects which you will require 
    #       Initialize algorithm related variables here
    
    #################################
    pass

def sysCall_actuation():
    # put your actuation code here
    # This function will be executed at each simulation time step

    ####### ADD YOUR CODE HERE ######
    # Hint: Use the error feedback and apply control algorithm here
    #       Provide the resulting actuation as input to the actuator joint
    
    # Example psuedo code:
    #   x1 = error_state_1; # Error in states w.r.t desired setpoint
    #   x2 = error_state_2;
    #   x3 = error_state_3;
    #   x4 = error_state_4;
    #   k = [gain_1 , gain_1, gain_3, gain_4];      # These gains will be generated by control algorithm. For ex: LQR, PID, etc.
    #   U = -k[1]*x1 +k[2]*x2 -k[3]*x3 +k[4]*x4;    # +/- Sign convention may differ according to implementation
    #   Set_joint_actuation(U);                     # Provide this calculated input to system's actuator

    #################################
    motor = sim.getObjectHandle('/Base_B/Pivot_B/Arm_B/Elbow_motor_B')
    wheel = sim.getObjectHandle('/Base_B/Pivot_B/Arm_B/Elbow_motor_B/wheel_B')
    elbow = sim.getObjectHandle('/Base_B/Pivot_B/Arm_B/Elbow_free_B')
    pivot = sim.getObjectHandle('/Base_B/Pivot_B')
    elbow_angle = sim.getJointPosition(elbow)
    pivot_angle = sim.getJointPosition(pivot)
    motor_angle = sim.getJointPosition(motor)
    elbow_vel = sim.getJointVelocity(elbow)
    pivot_vel = sim.getJointVelocity(pivot)
    motor_vel = sim.getJointVelocity(motor)
    elbow_init = 0
    motor_init = 0
    pivot_init = 0
    elbow_init_vel = 0
    motor_init_vel = 0
    pivot_init_vel = 0
    
    omega = (motor_angle - motor_init)/29
    theta = (elbow_angle - elbow_init)
    alpha = (pivot_angle - pivot_init)
    omega_dot = omega/(0.01)
    theta_dot = theta/(0.01)
    alpha_dot = alpha/(0.01)
    U = (k[0]*alpha_dot + k[1]*alpha + k[2]*theta_dot - k[3]*theta - k[4]*omega_dot - k[5]*omega)
    sim.setJointTargetVelocity(motor,U)
    velocit = sim.getJointVelocity(motor)
    print(velocit)
    
    
    

def sysCall_sensing():
    # put your sensing code here
    # This function will be executed at each simulation time step
    
    ####### ADD YOUR CODE HERE ######
    # Hint: Take feedback here & do the error calculation
    
    #################################
    pass

def sysCall_cleanup():
    # do some clean-up here
    # This function will be executed when the simulation ends
    
    ####### ADD YOUR CODE HERE ######
    # Any cleanup (if required) to take the scene back to it's original state after simulation
    # It helps in case simulation fails in an unwanted state.
    #################################
    pass

# See the user manual or the available code snippets for additional callback functions and details
